import { chromium } from 'playwright';

const base = process.env.P25_BASE_URL || 'http://127.0.0.1:4173';
const browser = await chromium.launch({headless:true});
const page = await browser.newPage({viewport:{width:390,height:844}, reducedMotion:'reduce'});
const fail = msg => { throw new Error('P25 gate: '+msg); };
const assertVisible = async (selector, label) => {
  const locator = page.locator(selector).first();
  if (!(await locator.isVisible().catch(()=>false))) fail(label+' not visible');
};

await page.goto(base+'/game-premium.html', {waitUntil:'networkidle'});
await page.evaluate(() => {
  const s=document.createElement('style');
  s.textContent='*,*::before,*::after{animation:none!important;transition:none!important}';
  document.head.appendChild(s);
  document.body.classList.add('reduce');
});
await page.evaluate(() => document.fonts.ready);
await page.screenshot({path:'p25-shell-launcher.png',fullPage:true});
await assertVisible('#launcher .display', 'launcher display');
await assertVisible('#launcher .menu-kicker', 'launcher kicker');
await assertVisible('#launcher .menu-title', 'launcher title lockup');
await assertVisible('#launcher .menu-actions', 'launcher action hierarchy');
await assertVisible('#launcher .crest', 'launcher crest');
if (!(await page.locator('#launcher .menu-note').isVisible())) fail('launcher supporting note missing');
if (await page.locator('#launcher').evaluate(el => el.scrollWidth > el.clientWidth + 1)) fail('launcher horizontal overflow');
await page.getByRole('button',{name:'Start a new run'}).click();
await assertVisible('#event .event-layout', 'event composition');
await assertVisible('#event .event-meta', 'event metadata');
await assertVisible('#event .event-title', 'event title');
await assertVisible('#event .choice-panel', 'event choice panel');
if (await page.locator('#event').evaluate(el => el.scrollWidth > el.clientWidth + 1)) fail('event horizontal overflow');
await page.screenshot({path:'p25-shell-event.png',fullPage:true});
const firstChoice=page.locator("#choices .choice").first(); await firstChoice.focus(); await page.keyboard.press("ArrowDown"); if ((await page.locator("#choices .choice").nth(1).getAttribute("aria-selected")) !== "true") fail("choice keyboard focus state missing"); await page.getByRole("button",{name:"Open the Hall"}).click();
await assertVisible('#consequence .consequence-layout', 'consequence composition');
await assertVisible('#consequence .consequence-meta', 'consequence decision marker');
await assertVisible('#consequence #consequenceChoice', 'consequence chosen option');
await assertVisible('#consequence #effectGrid', 'consequence effect grid');
await assertVisible('#consequence #stateStatus', 'consequence memory status');
if (!(await page.locator('#consequence #consequenceChoice').textContent()).includes('Open the Hall')) fail('chosen option not surfaced in consequence');
if (!(await page.locator('#consequence #effectGrid .stat').count())) fail('consequence effect values missing');
await page.screenshot({path:'p25-shell-consequence.png',fullPage:true});
await page.getByRole('button',{name:/Continue the chronicle/}).click();
await assertVisible('#event .choice-panel', 'choice chamber');
await page.getByRole('button',{name:'Kingdom'}).click();
await assertVisible('#kingdom .map', 'kingdom map');
await assertVisible('#kingdom .kingdom-side', 'kingdom state panel');
if (await page.locator('#kingdom [data-kingdom-node]').count() !== 6) fail('kingdom canonical node count mismatch');
for (const n of ['Crown','Commons','Noble','Guild','Border / Security','Civic / Medical']) if (!(await page.getByRole('button',{name:n,exact:true}).count())) fail('missing kingdom node '+n);
await page.getByRole('button',{name:'Crown',exact:true}).click();
if ((await page.locator('#kingdomFocusTitle').textContent()) !== 'Crown') fail('kingdom node selection not rendered');
if ((await page.getByRole('button',{name:'Crown',exact:true}).getAttribute('aria-pressed')) !== 'true') fail('kingdom selected state missing');
await page.getByRole('button',{name:'Crown',exact:true}).focus();
await page.keyboard.press('ArrowRight');
if ((await page.getByRole('button',{name:'Commons',exact:true}).getAttribute('aria-pressed')) !== 'true') fail('kingdom keyboard navigation state missing');
if ((await page.locator('#kingdomFocusTitle').textContent()) !== 'Commons') fail('kingdom keyboard selection not rendered');
if (!(await page.locator('#kingdomStats .stat').count() === 4)) fail('kingdom run metrics missing');
if ((await page.locator('#kingdom .map').textContent()).includes('Avelune')) fail('non-canonical realm name leaked');
await page.screenshot({path:'p25-shell-kingdom.png',fullPage:true});
await page.getByRole('button',{name:'People'}).click();
await assertVisible('#people .people', 'people presentation');
if (await page.locator('#people [data-kind="person"]').count() !== 6) fail('canonical people count mismatch');
for (const n of ['Mara','Rowan','Seris','Ivo','Amara','Toma']) if (!(await page.getByText(n,{exact:true}).count())) fail('missing canonical person '+n);
for (const n of ['Mara','Rowan','Seris','Ivo','Amara','Toma']) if (!(await page.getByRole('article',{name:new RegExp('Open canonical details for '+n)}).count())) fail('person card interaction missing '+n);
await page.getByRole('article',{name:/Open canonical details for Mara/}).focus();
await page.keyboard.press('ArrowRight');
if (!(await page.getByRole('article',{name:/Open canonical details for Rowan/}).evaluate(el=>document.activeElement===el))) fail('people keyboard navigation missing');
await page.getByRole('article',{name:/Open canonical details for Mara/}).click();
if (!(await page.getByRole('dialog').isVisible())) fail('people detail dialog missing');
if ((await page.getByRole('dialog').getAttribute('aria-hidden')) !== 'false') fail('people detail dialog aria state missing');
await page.getByRole('button',{name:'Close details'}).click();
await page.screenshot({path:'p25-shell-people.png',fullPage:true});
await page.getByRole('button',{name:'Factions'}).click();
await assertVisible('#factions .factions', 'factions presentation');
if (await page.locator('#factions [data-kind="faction"]').count() !== 6) fail('canonical institution card count mismatch');
for (const n of ['Crown','Commons','Noble','Guild','Border / Security','Civic / Medical']) if (!(await page.getByRole('button',{name:new RegExp('Open canonical details for '+n)}).count())) fail('institution card interaction missing '+n);
await page.getByRole('button',{name:/Open canonical details for Crown/}).focus();
await page.keyboard.press('ArrowRight');
if (!(await page.getByRole('button',{name:/Open canonical details for Commons/}).evaluate(el=>document.activeElement===el))) fail('institution keyboard navigation missing');
await page.getByRole('button',{name:/Open canonical details for Crown/}).click();
if (!(await page.getByRole('dialog').isVisible())) fail('institution detail dialog missing');
if (!(await page.getByText(/does not assign invented territory/).count())) fail('institution canon boundary missing');
await page.getByRole('button',{name:'Close details'}).click();
await page.getByRole('button',{name:'Investigation'}).click();
await assertVisible('#investigation .board', 'investigation board');
if (await page.locator('#investigation [data-evidence-index]').count() !== 4) fail('investigation route count mismatch');
for (const n of ["Mara's route","Toma's route","Seris's route","Direct account route"]) if (!(await page.getByRole('button',{name:new RegExp(n)}).count())) fail('investigation route interaction missing '+n);
await page.getByRole('button',{name:/Mara's route/}).focus();
await page.keyboard.press('ArrowRight');
if (!(await page.getByRole('button',{name:/Toma's route/}).evaluate(el=>document.activeElement===el))) fail('investigation keyboard navigation missing');
await page.getByRole('button',{name:/Mara's route/}).click();
if (!(await page.getByRole('dialog').isVisible())) fail('investigation detail dialog missing');
if (!(await page.getByText(/canonical investigation anchor/).count())) fail('investigation canonical boundary missing');
if ((await page.getByRole('dialog').getAttribute('aria-hidden')) !== 'false') fail('investigation dialog aria state missing');
await page.getByRole('button',{name:'Close details'}).click();
await page.getByRole('button',{name:'History'}).click();
await assertVisible('#history .timeline', 'history timeline');
if (!(await page.locator('#history [data-history-index]').count() >= 1)) fail('history decision entry missing');
if (!(await page.getByRole('button',{name:/The First Petition/}).count())) fail('history E01 entry interaction missing');
await page.getByRole('button',{name:/The First Petition/}).focus();
await page.keyboard.press('ArrowDown');
if (!(await page.getByRole('button',{name:/The First Petition/}).evaluate(el=>document.activeElement===el))) fail('history keyboard navigation missing for single entry');
await page.getByRole('button',{name:/The First Petition/}).click();
if (!(await page.getByRole('dialog').isVisible())) fail('history detail dialog missing');
if (!(await page.getByText(/current run memory only/).count())) fail('history canon boundary missing');
if ((await page.getByRole('dialog').getAttribute('aria-hidden')) !== 'false') fail('history dialog aria state missing');
await page.getByRole('button',{name:'Close details'}).click();
await page.getByRole('button',{name:'Endings'}).click();
await assertVisible('#endings .ending-grid', 'endings identity grid');
if (await page.locator('#endings [data-ending-index]').count() !== 7) fail('canonical ending identity count mismatch');
for (const n of ['Steward','Iron Crown','Golden Compact','People’s Charter','Broken Diadem','Quiet Throne','Second Founder']) if (!(await page.getByRole('button',{name:new RegExp(n)}).count())) fail('missing canonical ending identity '+n);
await page.getByRole('button',{name:/Steward/}).focus();
await page.keyboard.press('ArrowRight');
if (!(await page.getByRole('button',{name:/Iron Crown/}).evaluate(el=>document.activeElement===el))) fail('ending keyboard navigation missing');
await page.getByRole('button',{name:/Steward/}).click();
if (!(await page.getByRole('dialog').isVisible())) fail('ending detail dialog missing');
if (!(await page.getByText(/does not claim that this ending is currently reached/).count())) fail('ending canon boundary missing');
if ((await page.getByRole('dialog').getAttribute('aria-hidden')) !== 'false') fail('ending dialog aria state missing');
await page.getByRole('button',{name:'Close details'}).click();
await page.getByRole('button',{name:'Settings'}).click();
await assertVisible('#settings .settings', 'settings surface');
if (!(await page.getByRole('button',{name:'Start a new run'}).count())) fail('premium launcher missing');
await page.getByRole('button',{name:'Kingdom'}).click();
await page.goBack({waitUntil:'networkidle'});
if (!(await page.locator('#event').evaluate(el=>el.classList.contains('active')))) fail('browser back did not restore event screen');
await page.goForward({waitUntil:'networkidle'});
if (!(await page.locator('#kingdom').evaluate(el=>el.classList.contains('active')))) fail('browser forward did not restore kingdom screen');
await page.goto(base+'/game-premium.html',{waitUntil:'networkidle'});
await page.getByRole('button',{name:'Start a new run'}).click();
if ((await page.locator('body').evaluate(el => el.scrollWidth <= document.documentElement.clientWidth + 1)) !== true) fail('compact launch overflow');
if ((await page.locator('#eventTitle').textContent()) !== 'The First Petition') fail('E01 not rendered');
if (!(await page.locator('#event .event-meta').isVisible())) fail('event metadata missing');
if (!(await page.locator('#event .choice-panel').isVisible())) fail('event choice chamber missing');
await page.getByRole('button',{name:/Open the Hall/}).click();
if (!(await page.locator('#stateStatus').textContent()).includes('open_petition_hall')) fail('consequence state not rendered');
await page.getByRole('button',{name:/Continue the chronicle/}).click();
if ((await page.locator('#eventTitle').textContent()) !== 'The Empty Chair') fail('E02 not reached');
await page.getByRole('button',{name:/Archive it and investigate/}).click();
await page.getByRole('button',{name:/Continue the chronicle/}).click();
if ((await page.locator('#eventTitle').textContent()) !== "A Captain's Warning") fail('E05 not reached');
await page.getByRole('button',{name:/Audit the guard/}).click();
await page.getByRole('button',{name:'Kingdom'}).click();
if (!(await page.locator('#kingdom').evaluate(el=>el.classList.contains('active')))) fail('kingdom not reached');

await page.getByRole('button',{name:'People'}).click();
for (const n of ['Mara','Rowan','Seris','Ivo','Amara','Toma']) if (!(await page.getByText(n,{exact:true}).count())) fail('missing canonical person '+n);
await page.getByRole('article',{name:/Open canonical details for Mara/}).click();
if (!(await page.getByRole('dialog').isVisible())) fail('people detail dialog missing');
if ((await page.getByRole('dialog').getAttribute('aria-hidden')) !== 'false') fail('people detail dialog aria state missing');
await page.keyboard.press('Tab');
if (!(await page.getByRole('button',{name:'Close details'}).evaluate(el=>document.activeElement===el))) fail('dialog focus did not stay trapped');
if (!(await page.getByRole('heading',{name:'Mara'}).count())) fail('Mara detail missing');
await page.getByRole('button',{name:'Close details'}).click();

await page.getByRole('button',{name:'Factions'}).click();
for (const n of ['Crown','Commons','Noble','Guild','Border / Security','Civic / Medical']) if (!(await page.getByText(n,{exact:true}).count())) fail('missing canonical institution '+n);
if (await page.locator('#factions [data-kind="faction"]').count() !== 6) fail('canonical institution count mismatch');
await page.getByRole('button',{name:/Open canonical details for Crown/}).click();
if (!(await page.getByText(/does not assign invented territory/).count())) fail('institution canon boundary missing');
if ((await page.getByRole('dialog').getAttribute('aria-hidden')) !== 'false') fail('institution dialog aria state missing');
await page.keyboard.press('Tab');
if (!(await page.getByRole('button',{name:'Close details'}).evaluate(el=>document.activeElement===el))) fail('institution dialog focus trap missing');
await page.getByRole('button',{name:'Close details'}).click();

await page.getByRole('button',{name:'Investigation'}).click();
for (const n of ["Mara's route","Toma's route","Seris's route","Direct account route"]) if (!(await page.getByText(n,{exact:true}).count())) fail('missing investigation route '+n);
if (await page.locator('#investigation [data-evidence-index]').count() !== 4) fail('investigation evidence card count mismatch');
await page.getByRole('button',{name:/Direct account route/}).click();
if (!(await page.getByText(/presentation only and does not invent hidden connections/).count())) fail('investigation boundary text missing');
await page.getByRole('button',{name:'Close details'}).click();
await page.getByRole('button',{name:'History'}).click();
if (!(await page.getByText('The First Petition',{exact:true}).count())) fail('history did not record E01');
if (!(await page.locator('#history .history-entry').count())) fail('history premium entry surface missing');
await page.getByRole('button',{name:/The First Petition/}).click();
if (!(await page.getByText(/Choice recorded:/).count())) fail('history recorded-choice detail missing');
if (!(await page.getByText(/current run memory only/).count())) fail('history detail boundary missing');
await page.getByRole('button',{name:'Close details'}).click();
await page.getByRole('button',{name:'Endings'}).click();
if (!(await page.getByRole('heading',{name:'Endings'}).count())) fail('endings surface missing');
if (!(await page.getByText('No ending is forced in this visual prototype.').count())) fail('ending boundary copy missing');
if (await page.locator('#endings [data-ending-index]').count() !== 7) fail('ending identity cards missing');
await page.getByRole('button',{name:/Second Founder/}).click();
if (!(await page.getByText(/Canonical ending identity/).count())) fail('ending identity label missing');
await page.getByRole('button',{name:'Close details'}).click();
await page.getByRole('button',{name:'Settings'}).click();
await assertVisible('#settings .settings[role="group"]', 'settings accessibility group');
for (const n of ['Large text','RTL preview','Reduced motion','Light / dark presentation']) {
  const t=page.getByRole('button',{name:n});
  if (!(await t.isVisible())) fail('settings control missing: '+n);
  if ((await t.getAttribute('aria-pressed')) !== 'false') fail('settings control aria state missing: '+n);
}
await page.getByRole('button',{name:'Large text'}).focus();
await page.keyboard.press('Enter');
if ((await page.getByRole('button',{name:'Large text'}).getAttribute('aria-pressed')) !== 'true') fail('large-text toggle state missing');
if (!(await page.getByText(/These controls change presentation only/).count())) fail('settings canon boundary missing');
if (!(await page.locator('#settingsSummaryText').textContent()).includes('Large text on')) fail('settings state summary missing');
const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1);
if (overflow) fail('horizontal overflow on compact layout');
await page.getByRole('button',{name:'Kingdom'}).click();
if (!(await page.locator('#kingdom .map').isVisible())) fail('kingdom cinematic surface missing');
await page.getByRole('button',{name:'Investigation'}).click();
if (!(await page.locator('#investigation .board').isVisible())) fail('investigation evidence surface missing');
await page.getByRole('button',{name:'History'}).click();
if (!(await page.locator('#history .timeline').isVisible())) fail('history timeline surface missing');
await page.getByRole('button',{name:'Endings'}).click();
if (!(await page.locator('#endings').isVisible())) fail('endings surface missing');
await page.getByRole('button',{name:'Settings'}).click();
await page.getByRole('button',{name:'Large text'}).click();
await page.getByRole('button',{name:'RTL preview'}).click();
await page.getByRole('button',{name:'Reduced motion'}).click();
await page.getByRole('button',{name:'Light'}).click();
await page.reload({waitUntil:'networkidle'});
if (!(await page.locator('html').evaluate(el=>el.dataset.theme==='light'))) fail('theme preference did not persist');
if (!(await page.locator('body').evaluate(el=>el.classList.contains('large')))) fail('large-text preference did not persist');
if (!(await page.locator('html').evaluate(el=>el.dir==='rtl'))) fail('RTL preference did not persist');
if (!(await page.locator('body').evaluate(el=>el.classList.contains('reduce')))) fail('reduced-motion preference did not persist');

await page.getByRole('button',{name:'Kingdom'}).click();
if (!(await page.locator('#kingdom').evaluate(el=>el.classList.contains('active')))) fail('navigation did not reach kingdom');
if (location.hash !== '#kingdom') fail('navigation hash did not update to kingdom');
await page.getByRole('button',{name:'People'}).click();
if (!(await page.locator('#people').evaluate(el=>el.classList.contains('active')))) fail('navigation did not reach people');
if (location.hash !== '#people') fail('navigation hash did not update to people');
await page.goBack({waitUntil:'networkidle'});
if (!(await page.locator('#kingdom').evaluate(el=>el.classList.contains('active')))) fail('browser back did not restore kingdom');
if (location.hash !== '#kingdom') fail('browser back did not restore kingdom hash');
await page.goForward({waitUntil:'networkidle'});
if (!(await page.locator('#people').evaluate(el=>el.classList.contains('active')))) fail('browser forward did not restore people');
if (location.hash !== '#people') fail('browser forward did not restore people hash');
await page.getByRole('button',{name:'History'}).click();
if (!(await page.locator('#history').evaluate(el=>el.classList.contains('active')))) fail('navigation continuity did not restore history');
if (location.hash !== '#history') fail('navigation continuity hash mismatch');


const body = await page.locator('body').innerText();
for (const forbidden of ['Avelune','Queen Elira','Lord Cael','River Compact','Arwen Vale','The Empty Granary','Royal Capital','Northern Marches','The Church','Trade Guilds','Southern Reach','Eastern Realms']) if (body.includes(forbidden)) fail('non-canonical legacy text leaked: '+forbidden);

await page.setViewportSize({width:1440,height:1000});
await page.goto(base+'/game-premium.html',{waitUntil:'networkidle'});
if (!(await page.getByRole('button',{name:'Start a new run'}).isVisible())) fail('expanded premium launcher failed');
await page.screenshot({path:'p25-v2-expanded.png',fullPage:true});
await page.setViewportSize({width:360,height:800});
await page.reload({waitUntil:'networkidle'});
if (!(await page.getByRole('button',{name:'Start a new run'}).isVisible())) fail('compact premium launcher failed');
await page.screenshot({path:'p25-v2-compact.png',fullPage:true});

// P25.14 responsive/safe-area matrix: verify the real premium surface across phone, tablet and desktop window classes.
const viewportMatrix = [
  {width:320,height:568,label:'phone-320'},
  {width:360,height:800,label:'phone-360'},
  {width:412,height:915,label:'phone-412'},
  {width:768,height:1024,label:'tablet-portrait'},
  {width:1024,height:768,label:'tablet-landscape'},
  {width:1440,height:1000,label:'desktop-expanded'}
];
for (const vp of viewportMatrix) {
  await page.setViewportSize({width:vp.width,height:vp.height});
  await page.goto(base+'/game-premium.html',{waitUntil:'networkidle'});
  if (!(await page.getByRole('button',{name:'Start a new run'}).isVisible())) fail('responsive launcher missing: '+vp.label);
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1);
  if (overflow) fail('responsive horizontal overflow: '+vp.label);
  if (!(await page.locator('.wrap').count())) fail('responsive shell missing: '+vp.label);
  await page.screenshot({path:'p25-14-'+vp.label+'.png',fullPage:true});
}
await page.goto(base+'/game-premium.html',{waitUntil:'networkidle'});
const responsiveCss = await page.locator('style').allTextContents();
const cssText = responsiveCss.join('\\n');
for (const token of ['viewport-fit=cover','env(safe-area-inset-top)','env(safe-area-inset-right)','env(safe-area-inset-bottom)','env(safe-area-inset-left)','@media(max-width:900px)','@media(max-width:600px)','@media(orientation:landscape)']) {
  if (!cssText.includes(token)) fail('responsive/safe-area contract missing: '+token);
}
await page.setViewportSize({width:390,height:844});
await page.reload({waitUntil:'networkidle'});
await page.getByRole('button',{name:'Start a new run'}).click();
if (!(await page.locator('#event .choice-panel').isVisible())) fail('phone event choice chamber missing');
if (await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1)) fail('phone event overflow');
await page.setViewportSize({width:844,height:390});
await page.reload({waitUntil:'networkidle'});
if (!(await page.getByRole('button',{name:'Start a new run'}).isVisible())) fail('landscape launcher missing');
if (await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1)) fail('landscape overflow');

await browser.close();
console.log('P25 interactive gate: PASS');
