import { chromium } from 'playwright';

const base = process.env.P25_BASE_URL || 'http://127.0.0.1:4173';
const browser = await chromium.launch({headless:true});
const page = await browser.newPage({viewport:{width:390,height:844}, reducedMotion:'reduce'});
const fail = msg => { throw new Error('P25 gate: '+msg); };
const assertVisible = async (selector, label) => {
  const locator = page.locator(selector).first();
  if (!(await locator.isVisible().catch(()=>false))) fail(label+' not visible');
};

await page.goto(base+'/game-premium.html', {waitUntil:'networkidle'});
await page.evaluate(() => {
  const s=document.createElement('style');
  s.textContent='*,*::before,*::after{animation:none!important;transition:none!important}';
  document.head.appendChild(s);
  document.body.classList.add('reduce');
});
await page.evaluate(() => document.fonts.ready);
await page.screenshot({path:'p25-shell-launcher.png',fullPage:true});
await assertVisible('#launcher .display', 'launcher display');
await assertVisible('#launcher .menu-kicker', 'launcher kicker');
await assertVisible('#launcher .menu-title', 'launcher title lockup');
await assertVisible('#launcher .menu-actions', 'launcher action hierarchy');
await assertVisible('#launcher .crest', 'launcher crest');
if (!(await page.locator('#launcher .menu-note').isVisible())) fail('launcher supporting note missing');
if (await page.locator('#launcher').evaluate(el => el.scrollWidth > el.clientWidth + 1)) fail('launcher horizontal overflow');
await page.getByRole('button',{name:'Start a new run'}).click();
await assertVisible('#event .event-layout', 'event composition');
await assertVisible('#event .event-meta', 'event metadata');
await assertVisible('#event .event-title', 'event title');
await assertVisible('#event .choice-panel', 'event choice panel');
if (await page.locator('#event').evaluate(el => el.scrollWidth > el.clientWidth + 1)) fail('event horizontal overflow');
await page.screenshot({path:'p25-shell-event.png',fullPage:true});
const firstChoice=page.locator("#choices .choice").first(); await firstChoice.focus(); await page.keyboard.press("ArrowDown"); if ((await page.locator("#choices .choice").nth(1).getAttribute("aria-selected")) !== "true") fail("choice keyboard focus state missing"); await page.getByRole("button",{name:"Open the Hall"}).click();
await assertVisible('#consequence .consequence-layout', 'consequence composition');
await assertVisible('#consequence .consequence-meta', 'consequence decision marker');
await assertVisible('#consequence #consequenceChoice', 'consequence chosen option');
await assertVisible('#consequence #effectGrid', 'consequence effect grid');
await assertVisible('#consequence #stateStatus', 'consequence memory status');
if (!(await page.locator('#consequence #consequenceChoice').textContent()).includes('Open the Hall')) fail('chosen option not surfaced in consequence');
if (!(await page.locator('#consequence #effectGrid .stat').count())) fail('consequence effect values missing');
await page.screenshot({path:'p25-shell-consequence.png',fullPage:true});
await page.getByRole('button',{name:/Continue the chronicle/}).click();
await assertVisible('#event .choice-panel', 'choice chamber');
await page.getByRole('button',{name:'Kingdom'}).click();
await assertVisible('#kingdom .map', 'kingdom map');
await assertVisible('#kingdom .kingdom-side', 'kingdom state panel');
if (await page.locator('#kingdom [data-kingdom-node]').count() !== 6) fail('kingdom canonical node count mismatch');
for (const n of ['Crown','Commons','Noble','Guild','Border / Security','Civic / Medical']) if (!(await page.getByRole('button',{name:n,exact:true}).count())) fail('missing kingdom node '+n);
await page.getByRole('button',{name:'Crown',exact:true}).click();
if ((await page.locator('#kingdomFocusTitle').textContent()) !== 'Crown') fail('kingdom node selection not rendered');
if ((await page.getByRole('button',{name:'Crown',exact:true}).getAttribute('aria-pressed')) !== 'true') fail('kingdom selected state missing');
await page.getByRole('button',{name:'Crown',exact:true}).focus();
await page.keyboard.press('ArrowRight');
if ((await page.getByRole('button',{name:'Commons',exact:true}).getAttribute('aria-pressed')) !== 'true') fail('kingdom keyboard navigation state missing');
if ((await page.locator('#kingdomFocusTitle').textContent()) !== 'Commons') fail('kingdom keyboard selection not rendered');
if (!(await page.locator('#kingdomStats .stat').count() === 4)) fail('kingdom run metrics missing');
if ((await page.locator('#kingdom .map').textContent()).includes('Avelune')) fail('non-canonical realm name leaked');
await page.screenshot({path:'p25-shell-kingdom.png',fullPage:true});
await page.getByRole('button',{name:'People'}).click();
await assertVisible('#people .people', 'people presentation');
await page.getByRole('button',{name:'Factions'}).click();
await assertVisible('#factions .factions', 'factions presentation');
await page.getByRole('button',{name:'Investigation'}).click();
await assertVisible('#investigation .board', 'investigation board');
await page.getByRole('button',{name:'History'}).click();
await assertVisible('#history .timeline', 'history timeline');
await page.getByRole('button',{name:'Endings'}).click();
await assertVisible('#endings .endings', 'endings surface');
await page.getByRole('button',{name:'Settings'}).click();
await assertVisible('#settings .settings', 'settings surface');
if (!(await page.getByRole('button',{name:'Start a new run'}).count())) fail('premium launcher missing');
await page.getByRole('button',{name:'Kingdom'}).click();
await page.goBack({waitUntil:'networkidle'});
if (!(await page.locator('#event').evaluate(el=>el.classList.contains('active')))) fail('browser back did not restore event screen');
await page.goForward({waitUntil:'networkidle'});
if (!(await page.locator('#kingdom').evaluate(el=>el.classList.contains('active')))) fail('browser forward did not restore kingdom screen');
await page.goto(base+'/game-premium.html',{waitUntil:'networkidle'});
await page.getByRole('button',{name:'Start a new run'}).click();
if ((await page.locator('body').evaluate(el => el.scrollWidth <= document.documentElement.clientWidth + 1)) !== true) fail('compact launch overflow');
if ((await page.locator('#eventTitle').textContent()) !== 'The First Petition') fail('E01 not rendered');
if (!(await page.locator('#event .event-meta').isVisible())) fail('event metadata missing');
if (!(await page.locator('#event .choice-panel').isVisible())) fail('event choice chamber missing');
await page.getByRole('button',{name:/Open the Hall/}).click();
if (!(await page.locator('#stateStatus').textContent()).includes('open_petition_hall')) fail('consequence state not rendered');
await page.getByRole('button',{name:/Continue the chronicle/}).click();
if ((await page.locator('#eventTitle').textContent()) !== 'The Empty Chair') fail('E02 not reached');
await page.getByRole('button',{name:/Archive it and investigate/}).click();
await page.getByRole('button',{name:/Continue the chronicle/}).click();
if ((await page.locator('#eventTitle').textContent()) !== "A Captain's Warning") fail('E05 not reached');
await page.getByRole('button',{name:/Audit the guard/}).click();
await page.getByRole('button',{name:'Kingdom'}).click();
if (!(await page.locator('#kingdom').evaluate(el=>el.classList.contains('active')))) fail('kingdom not reached');

await page.getByRole('button',{name:'People'}).click();
for (const n of ['Mara','Rowan','Seris','Ivo','Amara','Toma']) if (!(await page.getByText(n,{exact:true}).count())) fail('missing canonical person '+n);
await page.getByRole('article',{name:/Open canonical details for Mara/}).click();
if (!(await page.getByRole('dialog').isVisible())) fail('people detail dialog missing');
if ((await page.getByRole('dialog').getAttribute('aria-hidden')) !== 'false') fail('people detail dialog aria state missing');
await page.keyboard.press('Tab');
if (!(await page.getByRole('button',{name:'Close details'}).evaluate(el=>document.activeElement===el))) fail('dialog focus did not stay trapped');
if (!(await page.getByRole('heading',{name:'Mara'}).count())) fail('Mara detail missing');
await page.getByRole('button',{name:'Close details'}).click();

await page.getByRole('button',{name:'Factions'}).click();
for (const n of ['Crown','Commons','Noble','Guild','Border / Security','Civic / Medical']) if (!(await page.getByText(n,{exact:true}).count())) fail('missing canonical institution '+n);
await page.getByRole('article',{name:/Open canonical details for Crown/}).click();
if (!(await page.getByText(/does not assign invented territory/).count())) fail('institution canon boundary missing');
await page.getByRole('button',{name:'Close details'}).click();

await page.getByRole('button',{name:'Investigation'}).click();
for (const n of ["Mara's route","Toma's route","Seris's route","Direct account route"]) if (!(await page.getByText(n,{exact:true}).count())) fail('missing investigation route '+n);
await page.getByRole('button',{name:'History'}).click();
if (!(await page.getByText('The First Petition',{exact:true}).count())) fail('history did not record E01');
await page.getByRole('button',{name:'Endings'}).click();
if (!(await page.getByRole('heading',{name:'Endings'}).count())) fail('endings surface missing');
if (!(await page.getByText('No ending is forced in this visual prototype.').count())) fail('ending boundary copy missing');
await page.getByRole('button',{name:'Settings'}).click();
const overflow = await page.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1);
if (overflow) fail('horizontal overflow on compact layout');
await page.getByRole('button',{name:'Kingdom'}).click();
if (!(await page.locator('#kingdom .map').isVisible())) fail('kingdom cinematic surface missing');
await page.getByRole('button',{name:'Investigation'}).click();
if (!(await page.locator('#investigation .board').isVisible())) fail('investigation evidence surface missing');
await page.getByRole('button',{name:'History'}).click();
if (!(await page.locator('#history .timeline').isVisible())) fail('history timeline surface missing');
await page.getByRole('button',{name:'Endings'}).click();
if (!(await page.locator('#endings').isVisible())) fail('endings surface missing');
await page.getByRole('button',{name:'Settings'}).click();
await page.getByRole('button',{name:'Large text'}).click();
await page.getByRole('button',{name:'RTL preview'}).click();
await page.getByRole('button',{name:'Reduced motion'}).click();
await page.getByRole('button',{name:'Light'}).click();
await page.reload({waitUntil:'networkidle'});
if (!(await page.locator('html').evaluate(el=>el.dataset.theme==='light'))) fail('theme preference did not persist');
if (!(await page.locator('body').evaluate(el=>el.classList.contains('large')))) fail('large-text preference did not persist');
if (!(await page.locator('html').evaluate(el=>el.dir==='rtl'))) fail('RTL preference did not persist');
if (!(await page.locator('body').evaluate(el=>el.classList.contains('reduce')))) fail('reduced-motion preference did not persist');

const body = await page.locator('body').innerText();
for (const forbidden of ['Queen Elira','Lord Cael','River Compact','Arwen Vale','The Empty Granary','Royal Capital','Northern Marches','The Church','Trade Guilds','Southern Reach','Eastern Realms']) if (body.includes(forbidden)) fail('non-canonical legacy text leaked: '+forbidden);

await page.setViewportSize({width:1440,height:1000});
await page.goto(base+'/game-premium.html',{waitUntil:'networkidle'});
if (!(await page.getByRole('button',{name:'Start a new run'}).isVisible())) fail('expanded premium launcher failed');
await page.screenshot({path:'p25-v2-expanded.png',fullPage:true});
await page.setViewportSize({width:360,height:800});
await page.reload({waitUntil:'networkidle'});
if (!(await page.getByRole('button',{name:'Start a new run'}).isVisible())) fail('compact premium launcher failed');
await page.screenshot({path:'p25-v2-compact.png',fullPage:true});

await browser.close();
console.log('P25 interactive gate: PASS');
